# -*- coding: utf-8 -*-
"""PropuestaConcursoAPP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJ5Oh3fXAhNWqbS4FcdPs6Lv9rAu2WXa
"""

# Proyecto: ¿Qué tipo de inversor eres?
# Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez
# Descripción: App que determina el perfil del inversor y analiza acciones con Python.

#pip install streamlit yfinance

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

# 🎯 TÍTULO Y DESCRIPCIÓN

st.title("💸 ¿Qué tipo de inversor eres? Tu estilo, tu riesgo, tu inversión.")
st.write("")
st.title("✨ Tu estilo, tu riesgo, tu inversión.")
st.markdown("""
Esta app te ayuda a identificar tu *perfil de inversor* y analizar el comportamiento de acciones reales.""")
st.markdown("")
st.markdown("Elige tus preferencias y descubre cómo se ajustan a los distintos tipos de portafolio.")

# 🧭 CUESTIONARIO DE PERFIL

st.header("🧩 Cuestionario del inversor")

riesgo = st.radio("¿Qué nivel de riesgo estás dispuesta(o) a asumir?", ["Bajo", "Medio", "Alto"])

plazo = st.selectbox("¿Cuál es tu horizonte de inversión?", ["Corto plazo", "Mediano plazo", "Largo plazo"])

experiencia = st.slider("¿Qué tanto conoces sobre inversiones?", 0, 10, 5)

# Definir perfil del inversor según respuestas
if riesgo == "Bajo" and plazo == "Corto plazo":
    perfil = "Conservador"
elif riesgo == "Medio":
    perfil = "Equilibrado"
else:
    perfil = "Agresivo"

st.subheader(f"🎯 Tu perfil de inversor es: *{perfil}*")