# -*- coding: utf-8 -*-
"""PropuestaConcursoAPP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJ5Oh3fXAhNWqbS4FcdPs6Lv9rAu2WXa
"""

# Proyecto: ¿Qué tipo de inversor eres?
# Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez
# Descripción: App que determina el perfil del inversor y analiza acciones con Python.
# -----------------------------

pip install streamlit yfinance

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

# -----------------------------
# 🎯 TÍTULO Y DESCRIPCIÓN
# -----------------------------
st.title("💸 ¿Qué tipo de inversor eres?")
st.markdown("""
Esta app te ayuda a identificar tu *perfil de inversor* y analizar el comportamiento de acciones reales.
Elige tus preferencias y descubre cómo se ajustan a los distintos tipos de portafolio. 🚀
""")